# Generated by Django 3.0.3 on 2020-03-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
