# Generated by Django 3.0.3 on 2020-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Qcost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
