# Generated by Django 3.0.3 on 2020-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
